openapi: 3.0.0
info:
  title: CoinGecko API
  version: 1.0.0
servers:
  - url: https://api.coingecko.com
paths:
  /api/v3/simple/price:
    get:
      summary: Get live price of a cryptocurrency
      parameters:
        - in: query
          name: ids
          schema:
            type: string
          required: true
          description: CoinGecko coin ID (e.g. bitcoin)
        - in: query
          name: vs_currencies
          schema:
            type: string
          required: true
          description: Currency (e.g. usd, eur)
      responses:
        '200':
          description: Current price
  /api/v3/coins/{id}/market_chart:
    get:
      summary: Get market chart for a coin
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: vs_currency
          schema:
            type: string
          required: true
        - in: query
          name: days
          schema:
            type: string
          required: true
          description: 1, 7, 30, 90, 365, max
      responses:
        '200':
          description: Chart data
