openapi: 3.0.0
info:
  title: Binance Public API
  version: 1.0.0
servers:
  - url: https://api.binance.com/api/v3
paths:
  /ticker/price:
    get:
      summary: Get latest price for a symbol
      parameters:
        - in: query
          name: symbol
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Symbol price
  /ticker/24hr:
    get:
      summary: Get 24hr volume for a symbol
      parameters:
        - in: query
          name: symbol
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 24hr stats
